return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 40,
  height = 40,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 6,
  nextobjectid = 1,
  properties = {},
  tilesets = {
    {
      name = "Roguelike",
      firstgid = 1,
      class = "",
      tilewidth = 16,
      tileheight = 16,
      spacing = 1,
      margin = 0,
      columns = 57,
      image = "../../../../Documents/Kenney Assets/2D assets/Roguelike Base Pack/Spritesheet/roguelikeSheet_transparent.png",
      imagewidth = 968,
      imageheight = 526,
      objectalignment = "unspecified",
      tilerendersize = "tile",
      fillmode = "stretch",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      wangsets = {},
      tilecount = 1767,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 40,
      id = 1,
      name = "Ground/terrain",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt1UkKgDAQRNGAw6EcL+VwfSMoSBODgtCF/MXbf6oDGUMII/AzteHdk2tTa6Tv2y6VvrtO7x6riEqjEug6dVFvDEJ7TWJ9qb3o+0ff/vZS702lL7ddEy2HVbDP88297fP6S+bLDVtzW6+bPtlS4ba5LdW2AwAAAL6wAQOugV4="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 40,
      id = 2,
      name = "Ground overlay",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzt0kEOgjAQRuEJLBS8lILnINxDPYd6LDwRJXaSpsSkUgpdvJf8+y+TESH6v6oQqe1Oxd6aeY0xtXbXAN+rFHk7S5XerXV2Drih71vbqK6LZwu9YWpf88Olu+/su1nD0XMdzB4L/i/VD6pTF2Lb0rc0fHHhiwtfXDn7emN5Wk+Ovo+xdBnfb2oov053REREREREWzYC5mk9fA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 40,
      id = 3,
      name = "Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztWM1qFEEQzszsHjzlFFGE+HPKI0SfIODFrIG8gIobTz5ACIGNqFH0osGr3qPkIZKAiuDFq+JBfYtUsd1s7TdVPdWzEwiYD4qZ7unq/vrrqprZnZs7x1nCank6894u9WsbPFd8B6LvXZE3H3MZlfq1LYbkuyH8dw1+K441LG4j8E3xvQzP3lP7Q6mPkfy2Hfya9ItX5Mv4SX2/Qj9qZvXlnm9KP01HC1KzH0W973sxtrcdxp/FLZWn8tmW8hz1m2/Yv8UpXptqhifG5Tjm5/VhNMUdjkV4YlyOY35eH0bqbLGWeWMxhVR+7JN9JPsk+rz170oLbi8Vn8iP58Nz/kP2l+yf6PPkhnauV1tqmap/1+jZdbIbYownb7G9WNY5vu77+TXlLK6NeRv1etyz/RYz1limeQ6rCT+Gl6OWt6n3r3auy4l9ILp8f+RAywUZ/3FfKX5D0vhRNd2nnS1yk34Dut4N92uVzY2h1bnID7ncofh9QO2HwC+VC/GMNT8N62H8q0SuML97pX9OhIy7vWLyXj+YoTbLdySe7++M2MWzzY1lCczvBTHns37dXhiaS73wrC1+Uo9D2v8R2XHQQeZE5CjP4Zu4t0xCy9MVyDXkILFRTYyRygkLub8ltoGf5HAEXIehH+uCxs+qyZ5aFr9VtFhmDk97Yw43+2O7FeKF8/C+yEXt226WONawCvoNq2kNUS8edyncs/aDhji+QHtdqmzzIs670xtrxPakN62XHBf3tZvg5/mez+X3ma5fgn0t6no01YzT0G8vUQuwH9tvoL0ZNMn5rmpC7u+slC+iC/3a5Nw85JUFrHepd4QFXuOin1rNV1vb+i8itnPq9Cw1S/qOMrRpk7tt0HU97nqNc36z4azz+19wAodpwEA="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 40,
      id = 4,
      name = "Doors/windows/roof",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMBiACxBzD7Qj8ABNRgaGjwPtCDoAWaaBdgF+EDbI3TcKBie4wMLAcJGFdH2HgHoOk6GPFLccA7I5WRkYuFhJN6sAqOcPld0Hcks9klssgGwnIHYmw30mQD2mZOjDB7C5pRRYPpcxkmbOKqD6p0D8jER9AwUCh1jZB8o7x2mQf6jlht8gMSLyTy4Nwx2fG0B55y8L4fyzjIbuI+QGHxLzTh7QrWZ0TMfRWMT68di/HCi3Akl+BRXc6kWn8sUbi1uxieEDShS6wRxo30qonaZExHXLICnTSA0nWtlnjkOc3uFEyD5qpDVagsGSrkbBKBgFo2CwAQApUCWp"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 40,
      height = 40,
      id = 5,
      name = "Roof object",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzkEBAAAEBLCTSP92WvCwJVgCAAA7uq4HAAAAfDHR3QAx"
    }
  }
}
